[[example]]
day = 1
[example.chk]
all_matches = [['1', '2'], ['3', '8'], ['1', '5'], ['7', '']]
calibration_values = [12, 38, 15, 77]
a = 142
first_digits = ['2', '8', '1', '2', '4', '1', '7']
last_digits = ['9', '3', '3', '4', '2', '4', '6']
calibration_values_2 = [29, 83, 13, 24, 42, 14, 76]
b = 281
[example.inp]
a = '''
1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet
'''
b = '''
two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen
'''

[[example]]
day = 2
[example.chk]
a = 8
possible = [1, 2, 5]
game_one_fewest = [4, 2, 6]
game_two_fewest = [1, 3, 4]
game_three_fewest = [20, 13, 6]
game_four_fewest = [14, 3, 15]
game_five_fewest = [6, 3, 2]
minimum_power = [48, 12, 1560, 630, 36]
b = 2286
[example.inp]
a = '''
Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green
'''

[[example]]
day = 3
[example.chk]
not_parts = [114, 58]
a = 4361
[example.inp]
a = '''
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''
b = '<INPUT UNKNOWN>'
