[[example]]
day = 1
[example.chk]
all_matches = [['1', '2'], ['3', '8'], ['1', '5'], ['7', '']]
calibration_values = [12, 38, 15, 77]
a = 142
first_digits = ['2', '8', '1', '2', '4', '1', '7']
last_digits = ['9', '3', '3', '4', '2', '4', '6']
calibration_values_2 = [29, 83, 13, 24, 42, 14, 76]
b = 281
[example.inp]
a = '''
1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet
'''
b = '''
two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen
'''

[[example]]
day = 2
[example.chk]
first_game = "Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green"
game_1_sets = "3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green"
game_1_num = '1'
bag = [12, 13, 14]
possible = [1, 2, 5]
a = 8
game_one_fewest = [4, 2, 6]
game_two_fewest = [1, 3, 4]
game_three_fewest = [20, 13, 6]
game_four_fewest = [14, 3, 15]
game_five_fewest = [6, 3, 2]
minimum_power = [48, 12, 1560, 630, 36]
b = 2286
[example.inp]
a = '''
Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green
'''
[example.chk.games]
1 = [["3 blue", "4 red"], ["1 red", "2 green", "6 blue"], ["2 green"]]
2 = [["1 blue", "2 green"], ["3 green", "4 blue", "1 red"], ["1 green", "1 blue"]]
3 = [
    [
        "8 green",
        "6 blue",
        "20 red",
    ],
    [
        "5 blue",
        "4 red",
        "13 green",
    ],
    [
        "5 green",
        "1 red",
    ],
]
4 = [
    [
        "1 green",
        "3 red",
        "6 blue",
    ],
    [
        "3 green",
        "6 red",
    ],
    [
        "3 green",
        "15 blue",
        "14 red",
    ],
]
5 = [["6 red", "1 blue", "3 green"], ["2 blue", "1 red", "2 green"]]

[[example]]
day = 3
[example.chk]
not_parts = [114, 58]
symbol_positions = [[1, 3], [3, 6], [4, 3], [5, 5], [8, 3], [8, 5]]
a = 4361
first_gear = [467, 35]
first_gear_ratio = 16345
second_gear = [755, 598]
second_gear_ratio = 451490
sum_of_all_gear_ratios = 467835
[example.inp]
a = '''
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

[[example]]
day = 4
[example.chk]
first_line = "Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53"
card_one_winning_numbers = [41, 48, 83, 86, 17]
card_one_drawn_numbers = [83, 86, 6, 31, 17, 9, 48, 53]
card_one_wins = [83, 86, 17, 48]
card_one_points = 8
cards_winning_numbers = [[83, 86, 17, 48], [61, 32], [21, 1], [84], [], []]
card_scores = [8, 2, 2, 1, 0, 0]
a = 13
counts_after_card_one = { 1 = 1, 2 = 2, 3 = 2, 4 = 2, 5 = 2, 6 = 1 }
counts_after_card_two = { 1 = 1, 2 = 2, 3 = 4, 4 = 4, 5 = 2, 6 = 1 }
counts_after_card_three = { 1 = 1, 2 = 2, 3 = 4, 4 = 8, 5 = 6, 6 = 1 }
counts_after_card_four = { 1 = 1, 2 = 2, 3 = 4, 4 = 8, 5 = 14, 6 = 1 }
counts_after_card_five = { 1 = 1, 2 = 2, 3 = 4, 4 = 8, 5 = 14, 6 = 1 }
counts_after_card_six = { 1 = 1, 2 = 2, 3 = 4, 4 = 8, 5 = 14, 6 = 1 }
b = 30
[example.inp]
a = '''
Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11
'''
