# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ccfb08c
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: false
github_repo_name: advent23
project_description: Collaboration on Advent of Code 2023
project_email: blake.naccarato@gmail.com
project_name: advent23
project_owner_github_username: blakeNaccarato
project_owner_name: blakeNaccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2023
