ci:
  autoupdate_schedule: "quarterly"

repos:
  - repo: "meta"
    hooks:
      # ? Enable this to ensure each hook runs against at least one file
      # - id: "check-hooks-apply"
      - id: "check-useless-excludes"
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
  - repo: "https://github.com/DavidAnson/markdownlint-cli2"
    rev: "v0.11.0"
    hooks:
      - id: "markdownlint-cli2-fix"
  - repo: "https://github.com/srstevenson/nb-clean"
    rev: "3.2.0"
    hooks:
      - id: "nb-clean"
        args:
          - "--remove-empty-cells"
          - "--preserve-cell-outputs"
          - "--preserve-cell-metadata"
          - "tags"
          - "--"
        files: |
          (?x)^(
            src/.*
            |docs/.*
            |tests/.*
          )$
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.1.9"
    hooks:
      - id: "ruff"
        types_or: ["python", "pyi", "jupyter"]
      - id: "ruff-format"
        types_or: ["python", "pyi", "jupyter"]
