name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  ruff:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "ruff --no-fix --output-format github ."
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "pytest"
