name: "pytest"

on: ["push", "workflow_dispatch"]

jobs:
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.1"
      - uses: "actions/setup-python@v4.7.1"
        with:
          python-version: "3.11"
      - run: "python -m pip install . --requirement requirements/requirements_ci.txt"
      - run: "pytest"
